name: Build & Analyze with Microwalk

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  analysis_script_directory: microwalk
  
jobs:
  build-analyze:
    runs-on: ubuntu-latest
    steps:
      # If necessary, add step for building the library / downloading necessary packages
      - uses: actions/checkout@v2
      
      - name: Run Microwalk analysis
        id: run_microwalk
        uses: microwalk-project/microwalk-jalangi2-action@v1
        with:
          # Change this if the analysis script is not in a /microwalk directory
          analysis-script-directory: ${{ env.analysis_script_directory }}
      
      - name: Upload analysis result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/${{ env.analysis_script_directory }}/results/report.sarif
          checkout_path: ${{ github.workspace }}
      
      - name: Archive analysis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: leakage-analysis-results
          path: ${{ github.workspace }}/${{ env.analysis_script_directory }}/results