name: Build Pin Tool

on:
  push:
    paths:
      - 'PinTracer/**'
  pull_request:
    paths:
      - 'PinTracer/**'
  workflow_dispatch:

jobs:
  build-pin-tool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Pin SDK
        run: |
          wget -O pin.tar.gz https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.27-98718-gbeaa5d51e-gcc-linux.tar.gz
          mkdir -p pin-sdk
          tar -xf pin.tar.gz -C pin-sdk/ --strip-components=1
      - name: Compile PinTracer
        run: |
          pinDir=`pwd`/pin-sdk
          cd PinTracer
          mkdir -p obj-intel64
          make PIN_ROOT="$pinDir" obj-intel64/PinTracer.so